#!/usr/bin/env sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell available, it is
#       recommended to use that to run this script.
#
#   (2) The Java home directory may need to be set explicitly with the
#       JAVA_HOME variable, if the shell's heuristic doesn't work correctly
#       for your system.
#
##############################################################################

if [ -z "$GRADLE_HOME" ] ; then
  GRADLE_HOME=$( cd -- "$( dirname -- "$0" )" > /dev/null && pwd )
fi
export GRADLE_HOME

CLASSPATH=$GRADLE_HOME/gradle-wrapper.jar

java "$@" -cp "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
